language: python
python:
  - "3.5"
# command to install dependencies
# command to run tests
install:
    - "python setup.py install"
    - "pip install coveralls"

script: "python setup.py test"

after_success:
    "coveralls"
