---
- name: install base package
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
      - software-properties-common

- name: add deadsnakes apt-repo
  shell: add-apt-repository -y ppa:fkrull/deadsnakes

- name: install system python packages
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
      - python3.5
      - python3.5-dev
      - python-pip
      - libpq-dev
      - libpcre3
      - libpcre3-dev

- name: install system virtualenv
  shell: pip install --upgrade virtualenv
