---
- hosts: tag_db
  roles:
      - role: postgres
        dbname: rlfarm

- hosts: tag_app
  roles:
      - role: python35

      - role: rlfarm
        username: webapp

      - role: nginx
        nginx_events_params:
            - worker_connections 512
            - debug_connection 127.0.0.1
            - use epoll
            - multi_accept on
        nginx_sites:
            default:
                - listen 80
                - server_name rlfarm.com
                - location / { uwsgi_pass unix:///tmp/uwsgi.sock; include uwsgi_params; }
