---
- hosts: tag_db
  roles:
      - role: postgres
        dbname: rlfarm

- hosts: tag_app

  vars:
      app_name: rlfarm
      username: webapp
      pip_package: https://github.com/wwitzel3/rlfarm/archive/master.zip
      domain: rlfarm.com

  roles:
      - role: python35

      - role: pyramid

      - role: nginx
        tags:
            - nginx
        nginx_events_params:
            - worker_connections 500
            - debug_connection 127.0.0.1
            - use epoll
            - multi_accept on
        nginx_sites:
            default:
                - listen 80
                - server_name {{ domain }}
                - return 301 https://{{ domain }}$request_uri
            www:
                - listen 80
                - server_name www.{{ domain }}
                - return 301 https://{{ domain }}$request_uri
            secure:
                - listen 443 ssl
                - keepalive_timeout 70
                - server_name {{ domain }}
                - ssl_certificate cert.key 
                - ssl_certificate_key private.key
                - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
                - ssl_ciphers HIGH:!aNULL:!MD5
                - ssl_session_cache shared:SSL:10m
                - ssl_session_timeout 10m
                - location / { uwsgi_pass unix:///tmp/uwsgi.sock; include uwsgi_params; }
                - location /static/ { alias /home/{{ username }}/env/lib/python3.5/site-packages/{{ app_name }}/static/; expires 30d; add_header Cache-Control public; access_log off; }
                - location /assets/ { alias /home/{{ username }}/env/lib/python3.5/site-packages/{{ app_name }}/static/assets/; expires 30d; add_header Cache-Control public; access_log off; }
