---
- name: install system packages
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
      - postgresql
      - postgresql-client
      - postgresql-contrib
      - python-psycopg2
      - makepasswd

- shell: makepasswd --chars=10
  register: dbuser

- shell: makepasswd --chars=10
  register: dbpass

- name: install pg_hba.conf
  template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf mode=0640 owner=postgres group=postgres

- name: install postresql.conf
  template: src=templates/postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf mode=0644 owner=postgres group=postgres

- name: restart service
  service: name=postgresql state=restarted enabled=yes

- name: install postgres sudo file
  template: src=templates/9999-ansible-postgres.j2 dest=/etc/sudoers.d/9999-ansible-postgres mode=0440 owner=root group=root

- name: create db '{{ dbname }}'
  postgresql_db: name={{ dbname }} state=present
  become_user: postgres
  become: true

- name: create db user
  postgresql_user:
      db='{{ dbname }}'
      name='{{ dbuser.stdout }}'
      password='{{ dbpass.stdout }}'
      role_attr_flags=NOSUPERUSER,NOCREATEDB
      state=present
  become_user: postgres
  become: true

- name: grant database permissions
  postgresql_privs:
      db='{{ dbname }}'
      type=database
      privs=ALL
      roles='{{ dbuser.stdout }}'
  become: true
  become_user: postgres

- name: grant table permissions
  postgresql_privs:
      db='{{ dbname }}'
      objs=ALL_IN_SCHEMA
      type=table
      privs=ALL
      roles='{{ dbuser.stdout }}'
  become: true
  become_user: postgres

- name: grant sequence permissions
  postgresql_privs:
      db='{{ dbname }}'
      objs=ALL_IN_SCHEMA
      type=sequence
      privs=ALL
      roles='{{ dbuser.stdout }}'
  become: true
  become_user: postgres

- name: export db details
  set_fact:
      dbport: "{{ dbport }}"
      dbname: "{{ dbname }}"
